### ISSUE TITLE
Add API functions to open and resolve disputes [$500]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#161] opened 2021-11-13 13:29 UTC
This issue requests [adding new API functions](https://github.com/haveno-dex/haveno/blob/master/docs/developer-guide.md#adding-new-api-functions-and-tests) to handle arbitration.

The following functions are requested as additions to [HavenoDaemon.ts](https://github.com/haveno-dex/haveno-ui-poc/blob/master/src/HavenoDaemon.ts) (feedback welcome).

| API Function | Return | Description
| --- | --- | --- |
| `havenod.openDispute(tradeId: string)` | `void` | Open a dispute (called by trader).
| `havenod.getDisputes()` | `Dispute[]` | Get all disputes.
| `havenod.getDispute(tradeId: string)` | `Dispute` | Get a dispute by trade id.
| `havenod.sendDisputeChatMessage(tradeId: string, message: string, attachments: Attachment[])` | `void` | Send a chat message between arbitrator and trader.
| `havenod.resolveDispute(tradeId: string, winner: DisputeResult.WINNER, reason: DisputeResult.REASON, summaryNotes: string, customWinnerAmount?: bigint)` | `void` | Resolve a disputed trade (called by arbitrator).

In addition, havenod should fire a notification when chat messages are received using existing APIs:

[`CoreNotificationService.sendNotification()`](https://github.com/haveno-dex/haveno/blob/1ae98094f322554c797e5f04da0727f960ce2d66/core/src/main/java/bisq/core/api/CoreNotificationService.java#L30) (back end)
[`havenod.addNotificationListener()`](https://github.com/haveno-dex/haveno-ui-poc/blob/6cc5228d7becbf7b6ffeddb5be82725f70e6bd74/src/HavenoDaemon.ts#L246) (front end)

### How to implement

Follow [these instructions](https://github.com/haveno-dex/haveno/blob/master/docs/developer-guide.md#adding-new-api-functions-and-tests) to add and test new API functions end-to-end.

We will add a new test, "Can resolve disputes", similar to the current test "Can complete a trade", which resolves the trade using a dispute.

For chat messages, see #142 and the ChatMessage and Attachment types in the [protobuf definition](https://github.com/haveno-dex/haveno/blob/cd108387a2b37e94194e014b44e26649533bb2de/proto/src/main/proto/pb.proto#L526).

**Comment by qophse** [comment] 2021-12-27 19:05
Hi, I'd like to take up this issue pending https://github.com/haveno-dex/haveno/issues/142

**Comment by woodser** [comment] 2021-12-27 20:00
Great. :) I've assigned it to you.

**Comment by woodser** [comment] 2022-02-02 13:13
How's it going @qophse?

**Comment by duriancrepe** [comment] 2022-02-09 20:35
Hi I'd like to work on this.

**Comment by erciccione** [comment] 2022-02-10 10:27
Assigning the issue to you @duriancrepe :)

**Comment by duriancrepe** [comment] 2022-02-14 19:43
It looks like `sendDisputeChatMessage(tradeId: String, ...)` should be modified to `sendDisputeChatMessage(disputeId: String)`. The reason is that the arbitrator needs to handle 2 disputes per trade, one for the dispute opener and one for the peer. With only the tradeId it is impossible to know which peer the arbitrator is trying to chat to.

**Comment by duriancrepe** [comment] 2022-02-15 03:19
Submitted pull requests.

**Comment by duriancrepe** [comment] 2022-02-15 16:38
The resolveDispute API is also a little different, rather than a single custom amount I allow the arbitrator to pass  the values to give to buyer / seller. 

Just realized perhaps the intention was to give the total security deposit to the winner or use a custom amount?

**Comment by woodser** [comment] 2022-02-15 21:11
Right the default is to award the trade amount to the winner and return both security deposits. If for some reason a custom amount is awarded to the winner (oops, this was missing from documentation), it would necessitate the other amount to the loser so I saw that field as redundant.

**Comment by woodser** [comment] 2022-02-15 21:15
> It looks like `sendDisputeChatMessage(tradeId: String, ...)` should be modified to `sendDisputeChatMessage(disputeId: String)`. The reason is that the arbitrator needs to handle 2 disputes per trade, one for the dispute opener and one for the peer. With only the tradeId it is impossible to know which peer the arbitrator is trying to chat to.

I'm trying to think of a use case for the arbitrator to resolve the dispute twice. The 2nd is a read-only copy of the first. Without knowing a good use case, this API was intended to resolve the dispute once which would notify both traders on the backend.

**Comment by duriancrepe** [comment] 2022-02-15 22:15
> I'm trying to think of a use case for the arbitrator to resolve the dispute twice. The 2nd is a read-only copy of the first. Without knowing a good use case, this API was intended to resolve the dispute once which would notify both traders on the backend.

The resolve dispute API in my implementation does just that, it remains `resolveDispute(tradeId: string)`, my proposed change is about the `sendChatMessage` API. The proposed implementation automatically resolve both peers' disputes, agree there isn't a use case to close only 1. Only the chat API requires a trader specific dispute.

The chatting functionality was implemented in a way where the trader clicks on their dispute.  Arbitrator sees both seller / taker and clicks on the corresponding seller / taker dispute to chat. My conjecture is that it was implemented in this way so that each peer sees their own side of the dispute without accidentally leaking chat or other data related to their side of the dispute to each other during the arbitration process.

Also quick update, I was able to implement and validate the chat message notifications for disputes, still need to correct the dispute payouts for the winner without custom amount.

**Comment by duriancrepe** [comment] 2022-02-16 21:45
Getting closer, but looks like there are some strange errors when closing the disputes, hitting:
`Feb-16 09:00:27.398 [HavenoDaemonMain] WARN  b.c.s.d.a.ArbitrationManager: Failed to sign dispute payout tx from arbitrator: null. TradeId = xbobak-0a8606b1-fe1c-4299-8671-e9b678bf18bc-162 `

**Comment by woodser** [comment] 2022-02-16 21:52
I can look into it when the code is updated.

**Comment by duriancrepe** [comment] 2022-02-16 22:52
I updated and rebased the code, ran the test and verified that I can repro the issue. My branch also prints in the transactionTx and verified the string is not null, it looks something like this:

`Failed to sign dispute payout tx from arbitrator: null. TradeId = dx331sq-1dddb59a-0c57-498d-994a-8a3ef0d23c36-162 SignedPayoutTx = 4d6f6e65726f206d756c746973696720756e7369676e656420747820736574018f98a0e084aee06cab3a0f2153dacc616486f98d86bebf7513af097b06509914dea94a35b23f4b7192f5a4b74a8fd114e48d5e5d2e41d14f652bf63e2ebac85c06859e178a4fbf0f19c034fc3ebbf263771824c643c05f564f84d49ebd95c1914d9eb2960fe3ac3389f0effd2ad6bbff55e0324a3046d2998ddef8d0defac8d...`

If you could help that would be great been stuck on it for awhile thanks!

**Comment by woodser** [comment] 2022-03-03 22:04
I haven't been able to reproduce the error `Failed to sign dispute payout tx from arbitrator: null` with the new ui test "Can resolve disputes".

You were still seeing it with your last commit?

**Comment by duriancrepe** [comment] 2022-03-04 02:06
Yes I still see it. I'm pretty sure my code flow and refactors is the same as if the disputes were resolved via the desktop UI. I will add some sleeps to see if I can find where the timing matters.

**Comment by woodser** [comment] 2022-03-04 02:15
I ran the test over 10 times and haven't reproduced it for some reason. You see it in Alice and Bob's console?

**Comment by duriancrepe** [comment] 2022-03-04 02:17
Yes I saw just saw it in Bob's console which fails the test because the fund is not returned. I will try more.

Are the tests fully succeeding on your end?

**Comment by woodser** [comment] 2022-03-04 02:26
I just saw it for the first time. I'll look into it.

**Comment by duriancrepe** [comment] 2022-03-04 02:34
If it helps my dev environment is quite slow and lacking ram and I am using the monero-shared stagenet

**Comment by duriancrepe** [comment] 2022-03-04 03:50
I hit a strange one, this time the trade and arbitration was done manually through the desktop:
```
[JavaFX Application Thread] WARN  b.core.support.SupportManager: Received AckMessage with error state for ChatMessage with tradeId 81161592-ae067f21-f6bd-4e32-8a98-23f5b90bde57-162 and errorMessage=Failed to sign dispute payout tx from arbitrator: Failed to sign multisig tx: This signature was made with stale data: export fresh multisig data, which other participants must then use.
```

**Comment by duriancrepe** [comment] 2022-03-04 06:01
I reordered the test so that the trade and dispute resolution is done sequentially and do not reproduce now. I think its related to the interleaved trade process that the disputes test exposed. 

I'm going to verify by running a few more times, but basically haven't reproduced the issue since then. Should I push the reordered dispute test logic confirming the dispute functionality is working fully?

**Comment by woodser** [comment] 2022-03-04 20:26
I'm suspecting the error is a result of too many wallets being open after running the test enough times (there are open todos to optimize wallet usage).

Are you able to reproduce the error within the first few test runs with fresh instances of Alice, Bob, and arbitrator?

**Comment by duriancrepe** [comment] 2022-03-04 21:25
I can, deleted the .local/share folders of alice bob and arbitrator and reproduced the first try. 

I restarted the funding wallet and monero-shared stagenet and still reproduced. 

Going to revert to master and see if I can reproduce under similar conditions.

**Comment by duriancrepe** [comment] 2022-03-04 21:39
I just tried a few times after doing some regular transaction and arbitration from the desktop app and now am not reproducing. One difference is that I now have some funds as the arbitrator.

My guess is this probably isn't a regression but a special case due to some initial conditions or test setup conditions but haven't been able to prove exactly what due to lack of ability to debug why that transaction is failing. 

I double checked the code refactors to enable the dispute API and am confident its the same logic (corrected 1 minor difference, pushed to pull request) but under different timing conditions.

**Comment by duriancrepe** [comment] 2022-03-05 00:42
I was able to reproduce on master after setting up a the trades so I am sure it is not a regression anymore. Here is the log for proof, note that is has the previous log format:

```
Buyer payout amount (with multiplier): 37500000000
Seller payout amount (with multiplier): 287500000000
Parsed arbitrator-signed payout tx:
=== TX ===
Fee: 622910000
Ring size: 11
Is confirmed: false
Num confirmations: 0
Unlock height: 0
Extra: null
Is outgoing: true
Outgoing transfer: 
  Is incoming: false
  Destinations: 
    1: 
      Address: 7AMKBXRBM3RC8uqdRBi2c2Y67vkidY7we7J4WW8NdX1u5iYWnzRzPNHVL2j7PxCJr2JaTRZLAUANH3N6xGJx9RNa7Uss9Wz
      Amount: 287188545000
    2: 
      Address: 76GUVetCXUZ22Aw8oUJD653BMht9oJvKhDFVpJ9NQMCx6Ga2xxXAW895rknfNPnKXZaaDV5X6xbJgM6rycYf5gyC7mWUzoB
      Amount: 37188545000
Input sum: 325000000000
Output sum: 324377090000
Change amount: 0
Num dummy outputs: 0
Extra hex: 01ca469256adf709a1a0fff7fe0e278ee7e0086fb3b39fbbc5757eae9e05da92b20402adb67084ce95758396c19e6a0c200155e15b430ff73ddd4aa4fb7861b8d0bcfad9c30a268f880e981f43bf8e58d8bbabb49855adaeeb5889bbea27d625f3bc7f
Mar-04 16:38:41.807 [HavenoDaemonMain] WARN  b.c.s.d.a.ArbitrationManager: Failed to sign dispute payout tx from arbitrator: null. TradeId = zwchokpq-0f133d37-6013-48a0-9d15-0b70ddbed7fb-162
```

**Comment by woodser** [comment] 2022-03-06 13:39
I finally found and fixed the NPE. It was the result of 0 change being sent back to the multisig wallet which only happens occasionally. I also updated the payout logic and tests so the winner receives the exact custom payout and the loser pays the mining fee.

Backend: https://github.com/duriancrepe/haveno/pull/3
Frontend: https://github.com/duriancrepe/haveno-ui-poc/pull/4

**Comment by duriancrepe** [comment] 2022-03-06 19:03
Thanks! I reviewed and merged your edits, rebased and ran the test and verify it succeeded.

**Comment by erciccione** [comment] 2022-03-12 09:20
Reward sent. Thanks @duriancrepe :)

**Comment by duriancrepe** [comment] 2022-03-12 09:24
Received, thank you!

**Closed** 2022-03-28 15:39 UTC
Labels: 💰bounty, P3, a:api
