### ISSUE TITLE
Suggestion: display the version number on the sign in password screen  (and perhaps elsewhere)

### ISSUE THREAD

**Issue by fareastbeach** [haveno-dex/haveno#1504] opened 2024-12-23 22:15 UTC
Suggestion: display the version number on the sign in password screen (and perhaps elsewhere)

At the moment you need to get Haveno running before you can see which version you are running.

Frequently problems are corrected by running the latest release, so to improve the support process, it really helps to know the version number from the earliest point that the software shows something.

That logic probably also applies to all error dialog boxes ... where a screen shot would then also include the software version number to help resolve a problem.

**Comment by phytohydra** [comment] 2024-12-23 23:40
You should have a file named desktop-1.0.17-SNAPSHOT.jar or desktop-1.0.17-SNAPSHOT-all.jar ?  That's the version.

`$ ./haveno-desktop --help | more`
```
Haveno Desktop version 1.0.17

Usage: haveno-desktop [options]

[...]
```

But it can be made more obvious.

**Comment by fareastbeach** [comment] 2024-12-24 01:13
This suggestion is aimed at getting important information from users who are basically non-technical,  who will not be able to search around in the file system and are  uncomfortable with the command line.   They are usually able to take a screenshot ...   so making the version number prominent at all times will help.

**Comment by phytohydra** [comment] 2024-12-28 02:21
Since the main view always has the version visible in the bottom status bar, between pull #1507 and #1513 this is mostly addressed, unless there are some other dialogs you can get where the main view isn't visible.

The problem is that some of the dialogs blur the main view to emphasize the dialog.  It's still legible if you squint.
Options:
Darken but don't blur
Blur less
Enumerate all those dialogs and add a redundant version string to them
Expect the user to squint

**Comment by fareastbeach** [comment] 2024-12-28 02:39
> Since the main view always has the version visible in the bottom status bar, between pull #1507 and #1513 this is mostly addressed, unless there are some other dialogs you can get where the main view isn't visible.
> 
> The problem is that some of the dialogs blur the main view to emphasize the dialog. It's still legible if you squint. Options: Darken but don't blur Blur less Enumerate all those dialogs and add a redundant version string to them Expect the user to squint

The main piece of this suggestion is to display the version on the signon screen - which is displayed before the main the  screen is presented .. at that point there is no visible feedback about the version available.  And if the signon or the startup process fails, the version remains not visible-and especially for a startup failure scenario it would be very useful if the version number was visible.

So we have both the sign on screen and the startup status screen that would be better if they displayed the version

**Comment by woodser** [comment] 2024-12-29 15:09
Resolved with https://github.com/haveno-dex/haveno/pull/1507 and https://github.com/haveno-dex/haveno/pull/1513.

**Closed by woodser** 2024-12-29 15:09 UTC
