### ISSUE TITLE
taking offer with a specific peer consistantly fails at "taking offer: 75%"

### ISSUE THREAD

**Issue by nihilist001** [haveno-dex/haveno#980] opened 2024-05-29 20:05 UTC
should not be tor related, but i may be wrong. Happened to me with the same peer 6 times out of 6 tries, when trying to take the offer, it consistantly fails at 75%
![image](https://github.com/haveno-dex/haveno/assets/139641914/8f354a20-2859-4774-a34d-a7b92b07ef5e)

haveno.log: https://paste.mozilla.org/cUdr3wne/raw

could it be that the other peer doesnt have the latest haveno version ?

**Comment by woodser** [comment] 2024-05-29 20:27
This can happen if you or the peer are consistently unable to create the deposit tx in enough time, which unfortunately is normal with Monero over Tor on a public node.

**Comment by woodser** [comment] 2024-06-04 12:10
Closing as this is normal when using Monero over Tor with public nodes.

The issue is resolvable by switching to a better node or using Monero over clearnet.

**Closed by woodser** 2024-06-04 12:10 UTC
