### ISSUE TITLE
Disable dependency on BTC node [$250]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#19] opened 2021-04-15 13:41 UTC
Currently Haveno depends on a Bitcoin node, Bitcoin-Qt, for proper startup and function.

This issue requests ~~removing this dependency completely~~ disabling the BTC dependency, since it's not necessary for XMR as a base pair.

**Comment by j7p2** [comment] 2021-04-22 18:55
Someone is working on removing the dependency of the btc node? I could work on that.

**Comment by niyid** [comment] 2021-04-22 23:42
> Someone is working on removing the dependency of the btc node? I could work on that.

I will suggest you hold on until it is confirmed that this dependency is no longer there on the removal of the DAO components.

**Comment by erciccione** [comment] 2021-04-23 08:24
@niyid this is part of the effort of removing all DAO components. No need to wait, the sooner we get rid of the BTC dependency, the better.

**Comment by woodser** [comment] 2021-04-23 14:49
> > Someone is working on removing the dependency of the btc node? I could work on that.
> 
> I will suggest you hold on until it is confirmed that this dependency is no longer there on the removal of the DAO components.

Yeah the BTC node might be used for atomic swaps.

In the meantime, it would be ideal if the BTC node can simply be disabled as a dependency (since technically it should not be needed).

**Comment by j7p2** [comment] 2021-05-09 13:44
I was holding as suggested. Should I look into that again? From my understanding the BTC node is only required when an exchange is being performed, so probably we should understand what is happening during the trade that requires the BTC node. Is it correct? I would look into that again if that's ok.

**Comment by woodser** [comment] 2021-05-09 13:52
Yeah the BTC node shouldn't be needed at any time to our knowledge, so we'd like to disable its use with a boolean flag.

>  so probably we should understand what is happening during the trade that requires the BTC node. Is it correct

Correct.  Last I knew it's checked to be running on startup too.

**Comment by premek** [comment] 2021-05-17 00:21
I will try to write down when I spot a BTC/node dependency being used somewhere

- [ ] lot of it will be in the DAO - should be removed in #13 
- [ ] `WalletsSetup`
  - [ ] `hasSufficientPeersForBroadcast`
  - [ ] `isDownloadComplete`
  - [ ] `isChainHeightSyncedWithinTolerance`

**Comment by erciccione** [comment] 2021-05-23 10:48
Because of the current price drop and volatility, we decided to set the bounty for this issue in dollars: $50 (will be still released in XMR). The bounty was previously set at 0.15 Moneroj, which is about $32 at the current XMR price.

**Comment by premek** [comment] 2021-06-13 22:52
It seems to me the btc node was used only in "full dao" mode

apart from that bitcoinj (java implementation of bitcoin node) is used in the code for BTC & BSQ wallets. BSQ wallet should be removed with the DAO, BTC wallet will be replaced with XMR (rpc) wallet

on some places bitcoinj connection to the bitcoin network is also used to check if it is fully synced, number of peers etc (see above)

**Comment by erciccione** [comment] 2021-09-02 16:45
Bounty bumped to $250

**Comment by chaserene** [comment] 2021-09-10 00:34
I'm bumping the bounty to $500 ($250 contribution from me, to be paid in XMR).

**Comment by chaserene** [comment] 2021-09-13 00:36
is @premek no longer working on this?

**Comment by erciccione** [comment] 2021-09-13 07:25
@chaserene this issue is currently unassigned and i don't think premek is working on it. Let me know if you wish to pick it up so i can assign it to you.

**Comment by premek** [comment] 2021-09-13 07:48
I believe this will be resolved after removing the DAO. I suggest wait for the dao-removal to be merged and the see if anything needs to be done

**Comment by premek** [comment] 2021-09-13 20:46
maybe until then someone could try what exactly fails if you don't run the btc node as it is now. To me it looked like it is not really required when you run haveno with `--daoActivated=false` as per the current install instructions. 
If we have a stacktrace or an error message (from running haveno without btc node) that would be a good start to remove the dependency.

**Comment by l0nelyc0w** [comment] 2021-09-25 21:09
I can confirm that remove DAO partially resolves this issue for the most part except in one point, during trade step "Confirm payment received" when peer presses "CONFIRM PAYMENT RECEIPT" button an error message pops upp "You need to wait until you have at least 1 connection to the Monero network.". 

Works like a charm up until then without starting BTC node.

**Comment by erciccione** [comment] 2021-10-21 16:41
Now that the DAO is removed (#121), anybody willing to resolve this issue?

**Comment by premek** [comment] 2021-10-21 16:50
Could you please assign it to me

**Comment by erciccione** [comment] 2022-01-07 11:14
Resolved with #207

**Comment by erciccione** [comment] 2022-01-07 11:47
Reward sent to @premek.

**Closed** 2022-01-07 11:48 UTC
Labels: is:enhancement, help wanted, 💰bounty, P3

**Comment by premek** [comment] 2022-01-07 11:54
received, thanks
