### ISSUE TITLE
Haveno crash at startup if LANG variable is modified

### ISSUE THREAD

**Issue by SyntheticBird45** [haveno-dex/haveno#905] opened 2024-05-14 17:12 UTC
`LANG=en_US.UTF-8 ./Haveno`

Results in:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.InternalError: Error loading java.security file
	at java.base/java.security.Security.initialize(Unknown Source)
	at java.base/java.security.Security.lambda$static$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.Security.<clinit>(Unknown Source)
	at java.base/sun.security.util.SecurityProperties.getOverridableProperty(Unknown Source)
	at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(Unknown Source)
	at java.base/sun.security.util.SecurityProperties.includedInExceptions(Unknown Source)
	at java.base/sun.security.util.SecurityProperties.<clinit>(Unknown Source)
	at java.base/sun.security.util.FilePermCompat.<clinit>(Unknown Source)
	at java.base/java.security.AccessControlContext.<init>(Unknown Source)
	at java.base/java.security.AccessController.createWrapper(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(Unknown Source)
	at java.base/java.util.ResourceBundle.loadBundle(Unknown Source)
	at java.base/java.util.ResourceBundle.findBundle(Unknown Source)
	at java.base/java.util.ResourceBundle.findBundle(Unknown Source)
	at java.base/java.util.ResourceBundle.findBundle(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundle(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.<clinit>(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.getLocalizedMessage(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.abort(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(Unknown Source)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by woodser** [comment] 2024-05-14 18:00
How are you setting the `LANG` variable, like `export LANG=`?

**Comment by Cyrix126** [comment] 2024-05-15 13:53
I can't reproduce the crash, which OS/DE are you using ?
is it instant or after a while ?

**Comment by SyntheticBird45** [comment] 2024-05-15 14:04
> How are you setting the `LANG` variable, like `export LANG=`?

As said in the issue message, I'm using the command: `LANG=en_US.UTF-8 ./Haveno`

**Comment by SyntheticBird45** [comment] 2024-05-15 14:04
> I can't reproduce the crash, which OS/DE are you using ? is it instant or after a while ?

Arch Linux/Gnome46/Wayland. It is instant

**Comment by nsec1** [comment] 2024-05-15 21:03
Which jdk are you using?

**Comment by SyntheticBird45** [comment] 2024-05-16 15:48
> Which jdk are you using?

```
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9)
OpenJDK 64-Bit Server VM (build 11.0.23+9, mixed mode)
```

**Comment by woodser** [comment] 2024-05-22 21:16
Closing this since it's likely caused by the outdated JDK. Please re-open if the problem persists after updating to JDK 21.

**Closed by woodser** 2024-05-22 21:16 UTC
