### ISSUE TITLE
Contracts are not matching

### ISSUE THREAD

**Issue by Cyrix126** [haveno-dex/haveno#981] opened 2024-05-30 08:33 UTC
I get this warning while taking an offer and the trade does not open.

![error_contracts](https://github.com/haveno-dex/haveno/assets/58007246/15ed402f-a9c5-4c5c-8d1d-431da38de7a1)

**Comment by nihilist001** [comment] 2024-05-30 08:41
encountered that same error too:
![image](https://github.com/haveno-dex/haveno/assets/139641914/d2642a7a-afd6-4b56-80d8-fa12dac9944f)

**Comment by woodser** [comment] 2024-05-30 12:49
@nihilist001 Can you provide the log output "Diff of both contracts:" ?

The diff is cutoff in your provided logs.

**Comment by nihilist001** [comment] 2024-05-30 12:53
> @nihilist001 Can you provide the log output "Diff of both contracts:" ?
> 
> The diff is cutoff in your provided logs.

full haveno.log of the day: https://paste.mozilla.org/ZFGPr2M3/raw

**Comment by woodser** [comment] 2024-05-30 14:50
The issue is caused by mismatching SEPA and SEPA instant. This will be fixed in the next release, but in the meantime the trade should succeed by using SEPA instead.

**Comment by nihilist001** [comment] 2024-05-30 16:30
> The issue is caused by mismatching SEPA and SEPA instant. This will be fixed in the next release, but in the meantime the trade should succeed by using SEPA instead.

got it, actually, it gives me the same error when trying to transact with a regular SEPA offer too

**Comment by woodser** [comment] 2024-05-30 16:45
The problem arises from taking a SEPA offer with a SEPA instant account.

**Comment by nihilist001** [comment] 2024-05-30 16:50
ok you're right, i tested it just now:

instant sepa acc -> instant sepa offer : fails at 75% (contracts not matching error)
instant sepa acc -> sepa offer : fails at 8% (contracts not matching error)
sepa acc -> sepa offer : succeeds just fine

**Comment by woodser** [comment] 2024-06-04 12:15
Fixed with https://github.com/haveno-dex/haveno/commit/b963fd501f9e976c07011691e9191df410b2ba20

**Closed by woodser** 2024-06-04 12:15 UTC
Labels: is:bug
