### ISSUE TITLE
a java error

### ISSUE THREAD

**Issue by shortwavesurfer2009** [haveno-dex/haveno#1121] opened 2024-07-10 10:13 UTC
![haveno_error](https://github.com/haveno-dex/haveno/assets/116814522/be729136-2091-4191-9af0-9a35bd300817)

log data:

Jul-10 06:01:22.215 [JavaFX Application Thread] ERROR h.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jul-10 06:01:22.216 [JavaFX Application Thread] ERROR h.c.s.CommonSetup: throwableMessage= Cannot read field "e" because "this.sorted[<parameter1>]" is null 
Jul-10 06:01:22.216 [JavaFX Application Thread] ERROR h.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Jul-10 06:01:22.219 [JavaFX Application Thread] ERROR h.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException: Cannot read field "e" because "this.sorted[<parameter1>]" is null
	at javafx.base/javafx.collections.transformation.SortedList.get(Unknown Source)
	at javafx.controls/javafx.scene.control.TableColumn.getCellObservableValue(Unknown Source)
	at javafx.controls/javafx.scene.control.TableCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.TableCell.indexChanged(Unknown Source)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.updateCells(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.checkState(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.computePrefHeight(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Unknown Source)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.resizeCell(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.addTrailingCells(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow$5.invalidated(Unknown Source)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellCount(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.updateItemCount(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualContainerBase.checkState(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.VirtualContainerBase.layoutChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.layoutChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
 
Jul-10 06:01:23.751 [NetworkNode.connectionExecutor:SendMessage-to-gixvz7ibl7ls...] INFO  h.n.p.n.NetworkNode: Socket creation to peersNodeAddress gixvz7ibl7lssv3jfbs2jkhge5emf736kakl26v2v4vdy4xeemzvnkyd.onion:9999 took 7332 ms 
Jul-10 06:01:23.754 [pool-22-thread-1] INFO  h.n.p.p.PeerManager: Num of latestLivePeers=23 
Jul-10 06:01:24.941 [NetworkNode.connectionExecutor:SendMessage-to-iasnz2sipuyo...] INFO  h.n.p.n.NetworkNode: Socket creation to peersNodeAddress iasnz2sipuyoarbbfbry4t7xoot5runxkw5u6zpkmcbpswxyqctxpjyd.onion:9999 took 10509 ms 
Jul-10 06:01:24.942 [pool-22-thread-1] INFO  h.n.p.p.PeerManager: Num of latestLivePeers=24 
Jul-10 06:01:25.060 [NetworkNode.connectionExecutor:SendMessage-to-x45z7nq3ezna...] INFO  h.n.p.n.NetworkNode: Socket creation to peersNodeAddress x45z7nq3eznaodz2qgz24ecchqvkcs5stgz3hngy5szpmyw2thtpxqad.onion:9999 took 12019 ms 

Edit: more details

1. I have my peer set to accept 1000 connections with --maxConnections=1000, i only get 70 to 90
2. I was in settings > network info and had clicked a peer in the peer list to highlight it and pressed and held down arrow to scroll the list
3. The list appears to wrap back to top once the bottom is reached and down arrow continues to be held. This might be what causes it

**Comment by woodser** [comment] 2024-07-10 11:23
The stacktrace doesn't point to its origin within haveno source. Do you know what screen you were on or what you were doing when the error occurred?

**Comment by shortwavesurfer2009** [comment] 2024-07-10 11:37
I was in settings > network info and was scrolling the list of peers by clicking one and scrolling with down arrow.

**Comment by woodser** [comment] 2024-08-13 17:36
Closing because related fixes were made in the last release, and the issue could be caused by rebuilding the app while it's running. Please re-open if you see it again.

**Closed by woodser** 2024-08-13 17:36 UTC
Labels: is:bug
